version: '2.1'

services:
  app:
    image: popstas/yandex-dialogs-smarthome-mqtt:v1.1.1
    build: .
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - $PWD/src/:/app/src/
      - $PWD/data/:/app/data/
    ports:
      - 5554:5554
